### ISSUE TITLE
Objects in "dormant/inactive" state appear active after migration

### ISSUE THREAD

**Issue by Espurna** [senaite/senaite.sync#38]
I noted that after the migration to a new instance, data that were "dormant / inactive" state now appear active again, for example, in departments, users, products, ect.

**Comment by nihadness** [comment]
@Espurna I just tested it and it seems objects with 'Dormant' and 'Inactive' states are migrated as expected (Methods, Departments, Lab Products). Maybe it is solved already. Could you please check and update this issue? Thank you!
